### ISSUE TITLE
Widget not on Hop Docs?

### ISSUE THREAD

**Issue by OfficialCRUGG** [askclippyai/widget#1]
Not sure if I'm understanding anything wrong, but according to your Readme, the Widget is available right now on the Live Version of the Hop Docs. The only problem is, it kind of isn't? Tried Arc, Chrome & Safari and even without caching,t he widget isn't on there.

**Comment by m1guelpf** [comment]
It should be! They're currently loading it using Google Tag Manager tho (working on fixing that), so you may have to disable adblock for it to work (didn't show up for me either at first because of uBlock in Arc).
